

export const MyFunctions ={
    searchFunction: function(){
        var test=document.getElementById("businessname").value;
        var business_name = ["Baby's",
        "Bazbeaux",
        "Beef & Boards Dinner Theatre",
        "Big Lug Canteen",
        "Bluemile Running Store",
        "BRU Burger Bar",
        "Cafe Patachou",
        "Canal Walk",
        "Caplinger's Fresh Catch",
        "Castleton Square Mall",
        "Conner Prairie",
        "Conrad Indianapolis",
        "Crowne Plaza Indianapolis Downtown Union Station",
        "Defy Indianapolis",
        "Drury Inn & Suites Indianapolis",
        "Easley Winery",
        "Embassy Suites Indianapolis Downtown",
        "Garfield Park Conservatory and Gardens",
        "Go Ape Treetop Adventure",
        "Goose the Market",
        "Harry & Izzy's",
        "Hotel Tango Distillery",
        "Hyatt Regency",
        "Indiana Grand Racing & Casino",
        "Indiana Historical Society",
        "Indiana Repertory Theatre",
        "Indianapolis Art Center",
        "Indianapolis City Market",
        "Indianapolis Motor Speedway",
        "Indianapolis Museum of Art at Newfields",
        "Indianapolis Zoo",
        "Jockamo Upper Crust Pizza",
        "Just Pop in Popcorn Cafe and Bar",
        "JW Marriott Indianapolis",
        "Kilroy's Bar and Grill",
        "Livery",
        "Lucas Oil Stadium",
        "Madam Walker Legacy Center",
        "Mama Carolla's Old Italian Restaurant",
        "Milktooth",
        "Mug 'N Bun",
        "Napolese Pizzeria",
        "Old World Gondoliers",
        "Punch Bowl Social",
        "Rick's Cafe Boatyard",
        "Ruoff Music Center",
        "Sahm's Tavern and Cafe",
        "Shapiro's Delicatessen",
        "Speedway Indoor Karting",
        "St. Elmo Steak House",
        "The Alexander",
        "The Children's Museum of Indianapolis",
        "The Fashion Mall, Keystone of the Crossing",
        "The HandleBar Indy Pedal Pub",
        "The Jazz Kitchen",
        "The Rathskeller",
        "The Tamale Place",
        "The Vogue",
        "Yats"]; 

        var business_type = ["Music & Nightlife",
        "Eat & Drink",
        "Arts & Culture",
        "Eat & Drink",
        "Shopping",
        "Eat & Drink",
        "Eat & Drink",
        "Sports & Recreation",
        "Eat & Drink",
        "Shopping",
        "Museums & Attractions",
        "Stay",
        "Stay",
        "Sports & Recreation",
        "Stay",
        "Arts & Culture",
        "Stay",
        "Museums & Attractions",
        "Sports & Recreation",
        "Eat & Drink",
        "Eat & Drink",
        "Shopping",
        "Stay",
        "Arts & Culture",
        "Arts & Culture",
        "Arts & Culture",
        "Arts & Culture",
        "Shopping",
        "Events",
        "Museums & Attractions",
        "Museums & Attractions",
        "Eat & Drink",
        "Music & Nightlife",
        "Stay",
        "Music & Nightlife",
        "Eat & Drink",
        "Events",
        "Museums & Attractions",
        "Eat & Drink",
        "Eat & Drink",
        "Eat & Drink",
        "Eat & Drink",
        "Sports & Recreation",
        "Eat & Drink",
        "Eat & Drink",
        "Events",
        "Eat & Drink",
        "Eat & Drink",
        "Sports & Recreation",
        "Eat & Drink",
        "Stay",
        "Museums & Attractions",
        "Shopping",
        "Music & Nightlife",
        "Music & Nightlife",
        "Eat & Drink",
        "Eat & Drink",
        "Music & Nightlife",
        "Eat & Drink"];

        var business_number = ["317-600-3559",
        "317-636-7662",
        "317-872-9664",
        "317-672-3502",
        "317-202-0202",
        "317-635-4278",
        "317-632-0765",
        "317-233-2434",
        "317-288-7263",
        "317-849-9994",
        "317-776-6000",
        "317-713-5000",
        "317-631-2221",
        "317-520-5030",
        "317-849-8900",
        "317-636-4516",
        "317-236-1800",
        "317-327-7183",
        "800-971-8271",
        "317-924-4944",
        "317-635-9594",
        "317-653-1806",
        "317-632-1234",
        "317-386-4463",
        "317-232-1182",
        "317-635-5277",
        "317-255-2464",
        "317-634-9266",
        "317-492-8500",
        "317-923-1331",
        "317-630-2001",
        "317-356-6612",
        "317-257-9338",
        "317-860-5800",
        "317-257-7849",
        "317-383-0330",
        "317-262-8600",
        "317-236-2099",
        "317-259-9412",
        "317-986-5131",
        "317-244-5669",
        "317-925-0765",
        "317-340-2489",
        "317-249-8613",
        "317-290-9300",
        "317-776-8181",
        "317-822-9903",
        "317-631-4041",
        "317-870-3780",
        "317-635-0636",
        "317-624-8200",
        "317-334-4000",
        "317-574-4000",
        "317-620-1448",
        "317-253-4900",
        "317-636-0396",
        "317-423-2203",
        "317-255-2828",
        "317-423-0518"];

        var business_address = ["2147 N Talbott St, Indianapolis, IN 46202",
        "333 Massachusetts Ave, Indianapolis, IN 46204",
        "9301 Michigan Rd, Indianapolis, IN 46268",
        "1435 E 86th St, Indianapolis, IN 46240",
        "1079 Broad Ripple Ave, Indianapolis, IN 46220",
        "410 Massachusetts Ave, Indianapolis, IN 46204",
        "255 W Washington St, Indianapolis, IN 46204",
        "420 W Ohio St, Indianapolis, IN 46292",
        "7460 Shadeland Ave, Indianapolis, IN 46250",
        "6020 E 82nd St, Indianapolis, IN 46250",
        "13400 Allisonville Rd, Fisher, IN 46038",
        "50 W Washington St, Indianapolis, IN 46204",
        "123 W Louisiana St, Indianapolis, IN 46225",
        "8356 Masters Rd, Indianapolis, IN 46250",
        "8180 Shadeland Ave, Indianapolis, IN 46250",
        "205 N College Ave, Indianapolis, IN 46202",
        "110 W Washington St, Indianapolis, IN 46204",
        "2505 Conservatory Dr, Indianapolis, IN 46203",
        "5855 Delong Road, Indianapolis, IN 46254",
        "2503 N Delaware St, Indianapolis, IN 46205",
        "153 South Illinois Street, Indianapolis, IN 46225",
        "702 Virginia Ave, Indianapolis, IN 46203",
        "1 S Capitol Ave, Indianapolis, IN 46204",
        "4300 N Michigan Rd, Shelbyville, IN 46176",
        "450 W Ohio St, Indianapolis, IN 46202",
        "140 W Washington St, Indianapolis, IN 46204",
        "820 E 67th St, Indianapolis, IN 46220",
        "222 E Market St, Indianapolis, IN 46220",
        "4790 W 16th St, Indianapolis, IN 46222",
        "4000 N Michigan Rd, Indianapolis, IN 46208",
        "1200 W Washington St, Indianapolis, IN 46222",
        "5646 E Washington St, Indianapolis, IN 46219",
        "6406 Cornell Ave, Indianapolis, IN 46220",
        "10 S West St, Indianapolis, IN 46204",
        "831 Broad Ripple Ave, Indianapolis, IN 46220",
        "720 N College Ave, Indianapolis, IN 46202",
        "500 S Capitol Ave, Indianapolis, IN 46225",
        "617 Indiana Ave, Indianapolis, IN 46202",
        "1031 E 54th St, Indianapolis, IN 46220",
        "534 Virginia Ave, Indianapolis, In 46203",
        "5211 W 10th St, Speedway, IN 46224",
        "114 E 49th St, Indianapolis, IN 46205",
        "340 W Michigan St, Indianapolis, IN 46202",
        "120 S Meridian St, Indianapolis, IN 46225",
        "4050 Dandy Trail, Indianapolis, IN 46254",
        "12880 E 146th St, Noblesville, IN 45060",
        "433 N Capitol Ave, Indianapolis, IN 46204",
        "808 S Meridian St, Indianapolis, IN 46240",
        "1067 N Main St, Speedway, IN 46224",
        "127 Illinois St, Indianapolis, IN 46225",
        "333 South Delaware St, Indianapolis, IN 46204",
        "3000 N Meridian St, Indianapolis, IN 46208",
        "8702 Keystone Crossing, Indianapolis, IN 46240",
        "501 Madison Ave, Indianapolis, IN 46225",
        "5377 N College Ave, Indianapolis, IN 46220",
        "401 E Michigan St, Indianapolis, IN 46204",
        "5226 Rockville Road, Indianapolis, IN 46224",
        "6259 N College Ave, Indianapolis, IN 46220",
        "5363 North College Ave, Indianapolis, IN 46220"]

        var business_website =["https://babysindy.com/",
        "bazbeaux.com",
        "beefandboards.com",
        "sahmsalehouse.com/nora",
        "jackrabbit.com",
        "bruburgerbar.com",
        "cafepatachou.com",
        "downtownindy.org/venue/2087/downtown-indy-canal-walk",
        "https://www.caplingersfreshcatch.com/",
        "https://www.simon.com/mall/castleton-square",
        "https://www.visithamiltoncounty.com/things-to-do/attractions/conner-prairie/",
        "https://www.conradindianapolis.com/",
        "https://www.crowneplazaindydowntown.com/",
        "https://defy.com/locations/defy-indianapolis/",
        "https://www.druryhotels.com/locations/indianapolis-in/drury-inn-and-suites-indianapolis-northeast",
        "http://www.easleywinery.com/",
        "https://www.hilton.com/en/hotels/indwwes-embassy-suites-indianapolis-downtown/",
        "https://www.garfieldgardensconservatory.org/",
        "https://www.goape.com/location/indiana-indianapolis/",
        "https://www.goosethemarket.com/",
        "http://www.harryandizzys.com/locations/downtown-indianapolis/",
        "https://hoteltangowhiskey.com/",
        "https://www.hyatt.com/en-US/hotel/indiana/hyatt-regency-indianapolis/indri",
        "https://www.caesars.com/indiana-grand",
        "https://indianahistory.org/",
        "https://www.irtlive.com/",
        "https://www.indplsartcenter.org/",
        "http://www.indycm.com/",
        "https://www.indianapolismotorspeedway.com/",
        "https://discovernewfields.org/",
        "https://www.indianapoliszoo.com/",
        "http://www.jockamopizza.com/",
        "https://www.justpopinpopcorn.com/popcorn-cafe",
        "https://www.marriott.com/hotels/hotel-information/fitness-center/indjw-jw-marriott-indianapolis/",
        "https://www.kilroysindy.com/full-menu/",
        "https://www.livery-restaurant.com/",
        "https://www.lucasoilstadium.com/",
        "https://madamwalkerlegacycenter.com/",
        "mamacarollas.com",
        "https://www.milktoothindy.com/",
        "http://mug-n-bun.com/",
        "https://napolesepizzeria.com/locations/",
        "http://www.4gondola.com/",
        "https://punchbowlsocial.com/location/indianapolis",
        "ricksboatyard.com",
        "https://www.livenation.com/venue/KovZpvEk7A/ruoff-music-center-events",
        "sahmstavern.com",
        "https://shapiros.com/",
        "https://www.sikarting.com/",
        "stelmos.com",
        "https://www.thealexander.com/?utm_source=google&utm_medium=organic&utm_campaign=business_listing",
        "childrensmuseum.org",
        "https://www.simon.com/mall/the-fashion-mall-at-keystone",
        "https://handlebarindy.com/",
        "thejazzkitchen.com",
        "https://rathskeller.com/",
        "https://www.thetamaleplace.com/",
        "https://thevogue.com/",
        "https://yatscajuncreole.com/wp/"]

        var business_actions = ["Reduced occupancy, Recommended face coverings (Customer), Employees and staff are screened for COVID-19 symptoms before being allowed to work, All employees and staff must wear face coverings, 6 Feet Social Distancing, Temperatures of customer's taken at the door, QR code menus.",
        "Reduced occupancy, Required face coverings (Customer), Employees and staff are screened for COVID-19 symptoms before being allowed to work, All employees and staff must wear face coverings, 6 Feet Social Distancing",
        "Reduced occupancy, Required face coverings (Customer), Self-Service prohibited, Employees and staff are screened for COVID-19 symptoms before being allowed to work, All employees and staff must wear face coverings, 6 Feet Social Distancing, Cleaning Stations, Guest temperature screening, germicidal lighting has been installed, gift shop closed, plexiglass in box office.",
        "Required face coverings (Customer), Self-Service prohibited, Employees and staff are screened for COVID-19 symptoms before being allowed to work, All employees and staff must wear face coverings, Regular menu has been ceased and has become a marketplace with touchless curbside pickup and delivery.",
		"Reduced occupancy, Separate hours for elderly and vulnerable customers, Required face coverings (Customer), Employees and staff are screened for COVID-19 symptoms before being allowed to work, All employees and staff must wear face coverings, 6 Feet Social Distancing",
        "Reduced occupancy, Required face coverings (Customer), Employees and staff are screened for COVID-19 symptoms before being allowed to work, All employees and staff must wear face coverings",
        "Reduced occupancy, Required face coverings (Customer), Employees and staff are screened for COVID-19 symptoms before being allowed to work, All employees and staff must wear face coverings, 6 Feet Social Distancing, All locations but Broad Ripple closed.",
        "None Available",
        "Reduced occupancy, Required face coverings (Customer), Employees and staff are screened for COVID-19 symptoms before being allowed to work, All employees and staff must wear face coverings, 6 Feet Social Distancing",
        "Reduced occupancy, Employees and staff are screened for COVID-19 symptoms before being allowed to work, All employees and staff must wear face coverings, 6 Feet Social Distancing, Curbside Pickup now offered",
        "Reduced occupancy, Required face coverings (Customer), Employees and staff are screened for COVID-19 symptoms before being allowed to work, All employees and staff must wear face coverings, 6 Feet Social Distancing, More rigorous bathroom cleaning, only credit card",
        "Reduced occupancy, Required face coverings (Customer), Self-Service prohibited, Employees and staff are screened for COVID-19 symptoms before being allowed to work, All employees and staff must wear face coverings, 6 Feet Social Distancing, Cleaning Stations, Enhanced cleaning in rooms with Lysol, reduced amenity hours for cleaning.",
        "Reduced occupancy, Required face coverings (Customer), Employees and staff are screened for COVID-19 symptoms before being allowed to work, All employees and staff must wear face coverings, 6 Feet Social Distancing, Cleaning Stations, Flexible cancellation and change policy.",
        "Required face coverings (Customer), Employees and staff are screened for COVID-19 symptoms before being allowed to work, All employees and staff must wear face coverings, 6 Feet Social Distancing, Cleaning Stations, More frequent cleaning",
        "Reduced occupancy, Required face coverings (Customer), All employees and staff must wear face coverings, 6 Feet Social Distancing, Cleaning Stations, Transparent shields for check in and removing need for signatures and electronic payment",
        "Required face coverings (Customer), Employees and staff are screened for COVID-19 symptoms before being allowed to work, Take out options",
        "Reduced occupancy, Required face coverings (Customer), Self-Service prohibited, Employees and staff are screened for COVID-19 symptoms before being allowed to work, All employees and staff must wear face coverings, 6 Feet Social Distancing, Cleaning Stations, Updated cancellation and reservation policies",
        "Reduced occupancy, Required face coverings (Customer), Employees and staff are screened for COVID-19 symptoms before being allowed to work, All employees and staff must wear face coverings, 6 Feet Social Distancing, Paths are now marked for one-way traffic, no restrooms open, plant shop will be closed, no transactions will take place in person.",
        "Required face coverings (Customer), Employees and staff are screened for COVID-19 symptoms before being allowed to work, All employees and staff must wear face coverings, 6 Feet Social Distancing, Cleaning Stations, Staff wears gloves",
        "Required face coverings (Customer), Employees and staff are screened for COVID-19 symptoms before being allowed to work, All employees and staff must wear face coverings, No-contact pickup or delivery, no in person service. ",
        "Reduced occupancy, Required face coverings (Customer), Employees and staff are screened for COVID-19 symptoms before being allowed to work, All employees and staff must wear face coverings, 6 Feet Social Distancing, Contactless carry out and delivery",
        "Reduced occupancy, Required face coverings (Customer), Employees and staff are screened for COVID-19 symptoms before being allowed to work, All employees and staff must wear face coverings, 6 Feet Social Distancing",
        "Reduced occupancy, Required face coverings (Customer), Employees and staff are screened for COVID-19 symptoms before being allowed to work, All employees and staff must wear face coverings, 6 Feet Social Distancing, Limited service available - Food Service, Fitness Center (limited to 50% capacity), Pool (limited to 50% capacity)",
        "Required face coverings (Customer), Employees and staff are screened for COVID-19 symptoms before being allowed to work, All employees and staff must wear face coverings, 6 Feet Social Distancing, Cleaning Stations, Temperatures of guests taken at the door, increased cleaning, no-smoking anywhere,",
        "Reduced occupancy, Required face coverings (Customer), Employees and staff are screened for COVID-19 symptoms before being allowed to work, All employees and staff must wear face coverings, 6 Feet Social Distancing, Cleaning Stations, Guests must preform a health self-assessment prior, will remove any guests not complying.",
        "Reduced occupancy, Required face coverings (Customer), Employees and staff are screened for COVID-19 symptoms before being allowed to work, All employees and staff must wear face coverings, 6 Feet Social Distancing, New flow for entering and exiting the theatre, new air filtration system",
        "Reduced occupancy, Recommended face coverings (Customer), Required face coverings (Customer), Employees and staff are screened for COVID-19 symptoms before being allowed to work, All employees and staff must wear face coverings, 6 Feet Social Distancing, Virtual Offerings, Cleaning Stations",
        "Reduced occupancy, Required face coverings (Customer), Employees and staff are screened for COVID-19 symptoms before being allowed to work, All employees and staff must wear face coverings, 6 Feet Social Distancing, Cleaning Stations, Outdoor Seating, Takeout, Delivery, Curbside Pickup",
        "Reduced occupancy, Required face coverings (Customer), Employees and staff are screened for COVID-19 symptoms before being allowed to work, All employees and staff must wear face coverings, 6 Feet Social Distancing, Cleaning Stations, More on plan to come",
        "Reduced occupancy, Required face coverings (Customer), Employees and staff are screened for COVID-19 symptoms before being allowed to work, All employees and staff must wear face coverings, 6 Feet Social Distancing",
        "Required face coverings (Customer), Employees and staff are screened for COVID-19 symptoms before being allowed to work, All employees and staff must wear face coverings, 6 Feet Social Distancing, Cleaning Stations, All cashless transactions",
        "Reduced occupancy, Required face coverings (Customer), Employees and staff are screened for COVID-19 symptoms before being allowed to work, All employees and staff must wear face coverings, 6 Feet Social Distancing, Cleaning Stations, Curbside carryout and phone orders.",
        "Contactless delivery and shipment.",
        "Reduced occupancy, Required face coverings (Customer), Employees and staff are screened for COVID-19 symptoms before being allowed to work, All employees and staff must wear face coverings, 6 Feet Social Distancing, Cleaning Stations, Plexiglass shields, TV remotes wrapped in plastic and no-touch digital food menus.",
        "Reduced occupancy, Required face coverings (Customer), Employees and staff are screened for COVID-19 symptoms before being allowed to work, All employees and staff must wear face coverings, 6 Feet Social Distancing",
        "Reduced occupancy, Required face coverings (Customer), Employees and staff are screened for COVID-19 symptoms before being allowed to work, All employees and staff must wear face coverings, 6 Feet Social Distancing, Outdoor seating",
        "Required face coverings (Customer), Employees and staff are screened for COVID-19 symptoms before being allowed to work, All employees and staff must wear face coverings, 6 Feet Social Distancing, Cleaning Stations, Health department input and approval for events, temperature and health screenings, adjusted traffic flow, 24/7 air circulation, plexiglass shields, touchless and cashless points of sale.",
        "Virtual Offerings, Closed temporarily",
        "Reduced occupancy, Required face coverings (Customer), Employees and staff are screened for COVID-19 symptoms before being allowed to work, All employees and staff must wear face coverings, 6 Feet Social Distancing, Outdoor dining and carryout.",
        "Required face coverings (Customer), Employees and staff are screened for COVID-19 symptoms before being allowed to work, All employees and staff must wear face coverings, 6 Feet Social Distancing",
        "Recommended face coverings (Customer), Required face coverings (Customer), Employees and staff are screened for COVID-19 symptoms before being allowed to work, All employees and staff must wear face coverings, 6 Feet Social Distancing, Drive Up Diner, so don't leave your car anyway unless you used limited seating.",
        "Reduced occupancy, Required face coverings (Customer), Employees and staff are screened for COVID-19 symptoms before being allowed to work, All employees and staff must wear face coverings, 6 Feet Social Distancing, curbside carryout + patio & socially-distanced indoor dining",
        "Reduced occupancy, Required face coverings (Customer), Employees and staff are screened for COVID-19 symptoms before being allowed to work, All employees and staff must wear face coverings, Customers must reserve private boats.",
        "Closed temporarily, opens October 1, 2020",
        "Reduced occupancy, Required face coverings (Customer), Employees and staff are screened for COVID-19 symptoms before being allowed to work, All employees and staff must wear face coverings, 6 Feet Social Distancing, Cleaning Stations, No contact ordering and payment.",
        "Required face coverings (Customer), Employees and staff are screened for COVID-19 symptoms before being allowed to work, All employees and staff must wear face coverings, 6 Feet Social Distancing, Socially distanced outdoor events.",
        "Temporarily Closed",
        "Reduced occupancy, Required face coverings (Customer), Employees and staff are screened for COVID-19 symptoms before being allowed to work, All employees and staff must wear face coverings, 6 Feet Social Distancing",
        "Reduced occupancy, Required face coverings (Customer), Employees and staff are screened for COVID-19 symptoms before being allowed to work, All employees and staff must wear face coverings, 6 Feet Social Distancing, Cleaning Stations, Personal equipment for purchase, plexiglass partition, air purifiers",
        "Reduced occupancy, Required face coverings (Customer), Employees and staff are screened for COVID-19 symptoms before being allowed to work, All employees and staff must wear face coverings, 6 Feet Social Distancing, Cleaning Stations, Reduced traffic slow",
        "Reduced occupancy, Required face coverings (Customer), Employees and staff are screened for COVID-19 symptoms before being allowed to work, All employees and staff must wear face coverings, 6 Feet Social Distancing, Cleaning Stations, waiving cancellation fees for direct bookings", 
        "Reduced occupancy, Required face coverings (Customer), Employees and staff are screened for COVID-19 symptoms before being allowed to work, All employees and staff must wear face coverings, 6 Feet Social Distancing, Cleaning Stations, Cashless transactions",
        "Reduced occupancy, Required face coverings (Customer), Employees and staff are screened for COVID-19 symptoms before being allowed to work, All employees and staff must wear face coverings, 6 Feet Social Distancing, Cleaning Stations",
        "Required face coverings (Customer), Employees and staff are screened for COVID-19 symptoms before being allowed to work, All employees and staff must wear face coverings, Cleaning Stations, Private group tours only",
        "Carryout only",
        "Reduced occupancy, Required face coverings (Customer), Employees and staff are screened for COVID-19 symptoms before being allowed to work, All employees and staff must wear face coverings, 6 Feet Social Distancing",
        "Reduced occupancy, Required face coverings (Customer), Employees and staff are screened for COVID-19 symptoms before being allowed to work, All employees and staff must wear face coverings, 6 Feet Social Distancing",
        "Reduced occupancy, Employees and staff are screened for COVID-19 symptoms before being allowed to work, All employees and staff must wear face coverings, 6 Feet Social Distancing, Cleaning Stations",
        "Required face coverings (Customer), Employees and staff are screened for COVID-19 symptoms before being allowed to work, All employees and staff must wear face coverings, 6 Feet Social Distancing, Outdoor dining or carryout"]

        var match = false;
        for(var i=0;i<60;i++)
        {
            if(test == business_name[i])
            {
                var results = document.getElementById("searchresults");
                results.innerHTML = business_name[i];

                results = document.getElementById("businesstype");
                results.innerHTML = business_type[i];

                results = document.getElementById("businessaddress");
                results.innerHTML = business_address[i];
                
                results = document.getElementById("businessnumber");
                results.innerHTML = business_number[i];

                results = document.getElementById("businesswebsite");
                results.innerHTML = business_website[i];

                results = document.getElementById("businessactions");
                results.innerHTML = business_actions[i];

                match = true;
            }
        }
        if(!match)
        {
            var message = document.getElementById("searchresults");
            message.innerHTML = "No results found.";
        }
        var push = document.getElementById("push");
        push.style.display = "block";
    }
}